### ISSUE TITLE
Timeout when using with docker

### ISSUE THREAD

**Issue by My42** [Neamar/riot-lol-api#25]
Hello,

I am making a application which use riot api.

When i use `riot-lol-api` without docker everything work, but when i use it i have timeout.

Do you have any sugestion ?

There is my docker container configuration : 

_docker-compose.yml_

<pre>
 server:
  container_name: leaf-server
  ports:
   - 8000:8000
  volumes:
   - ./packages/server:/opt/app
  build:
   context: ./packages/server
  depends_on:
   - database
  command: nodemon -L -e js,coffee,jade,handlebars app.js
</pre>

_dockerfile_:
<pre>
# Node container:
FROM node:10

ADD . /opt/app
WORKDIR /opt/app

USER root

RUN rm -rf node_modules \
 && npm install \
 && npm install -g nodemon

USER node

ENV HOME_DIR=/opt/app \
    NODE_CLUSTERED=1 \
    NODE_ENV=development \
    NODE_HOT_RELOAD=0 \
    PORT=8000

EXPOSE 8000 443 4242
</pre>

thanks,

**Comment by Neamar** [comment]
Hello!

Can you explain what you mean by timeout?

Also, try adding DEBUG=* and send your logs here (don't forget to redact your API key)

**Comment by My42** [comment]
Sorry, i forgot to answer you.. I found my problem, I was doing something wrong :man_facepalming:
