### ISSUE TITLE
Seeing a lot of 429 status code

### ISSUE THREAD

**Issue by Neamar** [Neamar/riot-lol-api#26]
Originally posted by @cohenu on https://github.com/Neamar/riot-lol-api/issues/21#issuecomment-458757058:

> Hey @nbs :-)
Did you managed to solve that issue? we have lots of 429 too. On our setup we have regional load balancer and in each region (2 in total - US & EU) we have node with this (wonderful, I have to say) library. each node server have 8 instance. we currently have around 10 million +/- requests per day (+ 2-7 hours of downtime from the blacklist) to Riot with throttler setup and we still got 429 (for example today we had 7,300 +/- 429s from eune, league endpoint)

> Any help on that issue will be very appreciated, Thanks in advanced!

**Comment by Neamar** [comment]
Hello!

That's a lot of 429 indeed.
I sent 120 million requests on the last 24 hours and only got 366 Rate Limit.

However, I don't use the league endpoint that much. I'm wondering if maybe you're hitting "Service Rate limit" as described in https://developer.riotgames.com/rate-limiting.html

The doc mentions that whenever this happens, the `X-Method-Rate-Limit-Count` is not set.

If you can, add some logging on https://github.com/Neamar/riot-lol-api/blob/b3ce7bee9fec8c3fac980083ec31bbb6a15dddf5/lib/index.js#L142-L158 to display `res.headers` and see if you can get a better understanding of what's going on in your use case.

Tell me if I can help!

**Comment by cohenu** [comment]
Thank you for the quick response! I believe you are correct, we think our issue is the service limit.

Do you have any advice regarding this issue ? is there anything that can be done on the library side or is there no way to avoid this ?

**Comment by Neamar** [comment]
From my understanding, this happens when the Riot API client (on Riot side) is blocked from accessing the resources.

The API acts as a gateway, and sometimes the underlying service return a 429.

The current behavior for this library is to read the requested Retry-After header and use it, and when it's not provided to wait for 2s before retrying:

https://github.com/Neamar/riot-lol-api/blob/b3ce7bee9fec8c3fac980083ec31bbb6a15dddf5/lib/index.js#L146

It seems that 2s is not enough for your use-case.
Can you easily hot-patch this to 10s and see if it improves the behavior for you? If it does, then it probably make sense to update the default value in the library.

**Comment by cohenu** [comment]
Thank you so much for the help!
We will test it out and post here if we have any luck with the fix. (We might even release a PR with an option to edit the value externally).

**Comment by Neamar** [comment]
Cool! Keep me updated 😎

**Comment by extrail** [comment]
Hey sorry for the delay,
Here is the promised PR: #27 
I'm not too sure how i can test this so I might need help with tests.
Changing the value to 10 did indeed mitigate the 429's.
