### ISSUE TITLE
Extreme amount of 429's

### ISSUE THREAD

**Issue by extrail** [Neamar/riot-lol-api#28]
Hey,
Sorry for the recent issues but i could really use some help.
We have a high throughput app with a complicated caching system (Redis & S3).
Recently we started getting an exaggerated amount of 429's once we reach a certain amount of requests.
We wanted to know if you have any insights.

We currently have 1 server with 8 cores with 3 instances of riot-lol-api deployed as a simple webserver.

**Comment by Neamar** [comment]
Hello! Sorry for the long delay.

The first thing I'd do is check whether those 429 are generated for your app, of if the service is down completely.

According to https://developer.riotgames.com/rate-limiting.html you can check `X-Rate-Limit-Type`: if it's not here or if it says "service", it's a service outage and there is nothing we can do about it.

If you do see a "application" header, then something else is going on!

**Comment by Neamar** [comment]
I'm going to close for now, if you get more information please post here and I'll reopen!
